Add basic employee rest service and controller test
fullstackhackathon/ConnectZuehlke pull request #1
Opened 2019-02-01 10:06 UTC by sebastianzillessen

2019-02-11 19:19 UTC, mariusreusch commented on build.gradle
> +    ext {
plugins { id 'java' }
plugins { id 'org.springframework.boot' version '2.1.2.RELEASE' }
plugins { id 'io.spring.dependency-management' version '1.0.6.RELEASE' }

group = 'ch.mare.springtraining'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '1.8'

repositories {
    mavenCentral()
}

2019-02-11 19:23 UTC, mariusreusch requested changes

2019-02-11 19:23 UTC, mariusreusch commented on build.gradle
> +    ext {
der erste teil bis zu dependcies section kann mit der neuen Gradle plugin Syntax ersetzt werden: 

plugins { id 'java' }
plugins { id 'org.springframework.boot' version '2.1.2.RELEASE' }
plugins { id 'io.spring.dependency-management' version '1.0.6.RELEASE' }

sourceCompatibility = '1.8'

repositories {
    mavenCentral()
}

2019-02-11 19:23 UTC, mariusreusch commented on build.gradle
> +    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.9.6'
braucht man das tataäschlich noch?

2019-02-12 09:51 UTC, sebastianzillessen commented on build.gradle
> +    ext {
Habs geändert.

2019-02-12 09:51 UTC, sebastianzillessen commented on build.gradle
> +    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.9.6'
Super, danke, kann man wirklich entfernen.

2019-02-12 09:54 UTC, merged